### PR TITLE
Change authManager

### PR DESCRIPTION
**Pull request by zacharlie**
The API for `QgsAuthManager.instance()` has changed to `QgsApplication.authManager()` to address #169

### CODE REVIEW

**Review by havatv — APPROVED** [review]
Looks fine to me.

**Comment by zacharlie** [comment]
I was just concerned more tests were required as I'm not 100% familiar with the API, but if it's OK I'll mark it as ready...

**Comment by zacharlie** [comment]
A indicated this removes the `type object 'QgsAuthManager' has no attribute 'instance'` error, but doesn't fix the authentication issue.

https://github.com/QGIS-Contribution/QGIS-ResourceSharing/issues/169

**Comment by Guts** [comment]
Hi @zacharlie,

Is this PR still necessary?

**Comment by zacharlie** [comment]
@Guts I don't believe so

**Pull request closed without merging**
