### PR TITLE
Create LICENSE

### LINKED ISSUE #173: Define a license for this source code
The repository is missing a license. @havatv let's pick one from 😄.

Reading https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository and https://choosealicense.com/, I would recommend:

- [ ] GPL 3
- [ ] MIT
- [ ] MPL

### PR DESCRIPTION
**Pull request by havatv**
Close #173

### CODE REVIEW

**Comment by havatv** [comment]
@Guts, I am having problems with this PR - no able to merge:

    flake8_py3 Expected — Waiting for status to be reported

**Comment by Guts** [comment]
> 
> 
> @Guts, I am having problems with this PR - not able to merge:
> 
> ```
> flake8_py3 Expected — Waiting for status to be reported 

Weird.
I'll have a look tonight.

**Comment by Guts** [comment]
Ah ok, got it: I've set the lint action as a required check ([here](https://github.com/QGIS-Contribution/QGIS-ResourceSharing/settings/branch_protection_rules/18026583)) but I've also set that the linter will trigger only if a Python file is changed.

I'll quickly remove this filter on paths to fix this side effect. Sorry for the inconvenience!

**Comment by Guts** [comment]
Done @havatv

**Pull request merged**
