### PR TITLE
Add more QGIS_REPO to travis: improvements for unit testing - fix #49

### LINKED ISSUE #49: QgsSymbolLayerV2Utils.loadSymbol does not load one symbol
I wildly commented this line https://github.com/akbargumbira/qgis_resources_sharing/blob/develop/test/test_symbol_xml_extractor.py#L32 so that all the unittests can pass and release a new version (supporting gogs and gitlab repository handler from @slarosa). 

But there is a bigger problem there that might be a problem in QGIS LTR. This line here https://github.com/akbargumbira/qgis_resources_sharing/blob/develop/resource_sharing/symbol_xml_extractor.py#L45 is to load a symbol from XML element. It failed to load one symbol from this xml here https://github.com/akbargumbira/qgis_resources_data/blob/master/collections/test_collection/symbol/various_symbols.xml. The symbol that can't be loaded is this one https://github.com/akbargumbira/qgis_resources_data/blob/master/collections/test_collection/symbol/various_symbols.xml#L83.  QgsSymbolLayerV2Utils.loadSymbol() for that symbol element gives None from sip API, so some fixes in QGIS is needed.

### PR DESCRIPTION
**Pull request by slarosa**
Add more QGIS versions to travis. Basically uses the same configuration of qgis2web plugin for testing.

### CODE REVIEW

**Comment by slarosa** [comment]
ooops...coverage is not my friend!

**Comment by slarosa** [comment]
ok...now coverage is my friend! :-)

**Comment by akbargumbira** [comment]
@slarosa any reason to use mocked QGIS app for the tests? I intentionally used QGIS testing class to promote @m-kuhn 's work last year. Though Boundless makes another testing framework using docker with QGIS instance inside (so the tests are run against a real QGIS instance)

**Comment by m-kuhn** [comment]
QGIS upstream also uses docker images for testing QGIS 3. This can also be used for plugins (see e.g. https://travis-ci.org/opengisch/projectgenerator), QGIS testing classes are available as well.

**Comment by slarosa** [comment]
No particular reason, just want to see travis happy :-) against more qgis version!
I will do a PR with docker image for testing as soon as possible taking inspiration from @mkhun's hint! Thanks.

**Comment by m-kuhn** [comment]
@slarosa 

You get extra points if you make a deploy on success of all builds with build stages ;) https://travis-ci.org/opengisch/projectgenerator/builds/281908128

**Comment by slarosa** [comment]
@m-kuhn and that should be an awesome score for my unit-testing game!

**Comment by akbargumbira** [comment]
@m-kuhn is there docker image for QGIS 3?

@slarosa more extra points if there is a QGIS 3 image and we also test it agains this version :) @elpaso started some work to port this to be ready for QGIS 3 as core plugins in this branch (https://github.com/akbargumbira/qgis_resources_sharing/tree/qgis3), but I haven't got time to finish it

**Comment by m-kuhn** [comment]
> @m-kuhn is there docker image for QGIS 3?

The one from the link above is qgis3.

One of the two does not change (fixed to a certain commit) the other one regularly gets updated to the latest master.

**Comment by slarosa** [comment]
> @slarosa any reason to use mocked QGIS app for the tests? I intentionally used QGIS testing class to promote @m-kuhn 's work last year.

Also, using the QGIS testing module (see https://github.com/slarosa/qgis_resources_sharing/commit/0abda99ad4f5f44447c4596b0549efc459fadebb) I got a bunch of ImportError (i.e ```ImportError: No module named qgis_resources_sharing.test.repository_handler.test_handler```), but was unclear to me on what could be the reason of the problem there:
https://travis-ci.org/slarosa/qgis_resources_sharing/jobs/297732453

**Comment by Guts** [comment]
This PR has long lived and tests have been refactored to fit Github Actions in #259.

**Pull request closed without merging**
