### PR TITLE
Add the plugin to the web menu

### PR DESCRIPTION
**Pull request by havatv**
Fixes: #68
Prepares for fixing #28

### CODE REVIEW

**Comment by havatv** [comment]
@elpaso, @akbargumbira, @anitagraser, @pcav, @timlinux - what do you think about this,

**Comment by pcav** [comment]
Not sure it belongs here. In fact it falls between web and styling.

**Comment by havatv** [comment]
> Not sure it belongs here. In fact it falls between web and styling.

Thanks for responding, @pcav.

In addition to styling (styles, SVGs, images), processing scripts and R scripts are currently supported.
The menus that are available for plugins are: **Web**, **Database** (also a possibility), **Plugins** (not possible to avoid submenu), **Raster** and **Vector**. The last two are not natural "hosts" for this plugin.

As @timlinux says in #28, the plugin belongs in the `Settings` menu, but currently it does not seem to be possible to include it there. This PR adds Resource Sharing to the Web menu, but it is still available in the Plugins menu.

With this PR merged, it will only be a matter of substituting the string "Web" with "Settings" two places in plugin.py to move it to the Settings menu (once that has been made possible).

**Comment by pcav** [comment]
Thanks @havatv for the detailed explanation, quite convincing to me.
+1 for your solution then.

**Comment by havatv** [comment]
Lack of negative input and very low potential for breaking anything, so I merged.

**Pull request merged**
